version: '3'
tasks:

  clone:
    - git clone https://github.com/apache/openwhisk-deploy-kube
    - mkdir export

  export:
    cmds:
    - | 
      if test -z "{{.FILE}}"
      then ls "{{.TPL}}/templates" ; echo select with "FILE=<file>" no .yaml
      else helm template {{.TPL}} \
      -n nuvolaris -f openwhisk-deploy-kube/deploy/kind/mycluster.yaml \
      -s  templates/{{.FILE}}.yaml
      fi
    vars:
      TPL: openwhisk-deploy-kube/helm/openwhisk