version: '3'

vars:
  CMD: apply

tasks:

  init:
    - kubectl apply -f init
    - kubectl config set-context --current --namespace nuvolaris
    
  couchdb: 
     - kubectl {{.CMD}} -f couchdb

  redpanda: 
     - kubectl {{.CMD}} -f redpanda

