apiVersion: v1
kind: Pod
metadata:
  name: kcat
  namespace: nuvolaris
  labels:
    app: kcat
spec:
  containers:
   - name: kcat
     image: edenhill/kcat:1.7.1
     command: ["/bin/sh", "-c",  "tail -f /dev/null"] 
     